[package]
name = "kuzstu_shedule_using_api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = {version = "1.0.210", features = ["derive"] }
tera = "1.20.0"
